site_name: Отчёты по WEB-программированию — Мещеряков Даниил (K3340)

theme:
  name: material
  language: ru
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Переключить на тёмную тему
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Переключить на светлую тему
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

nav:
  - Главная: index.md
  - Лабораторная работа №1:
      - Описание: lab1/docs/index.md
      - Задание 1: lab1/docs/task1.md
      - Задание 2: lab1/docs/task2.md
      - Задание 3: lab1/docs/task3.md
      - Задание 4: lab1/docs/task4.md
      - Задание 5: lab1/docs/task5.md
  - Практическая работа №2 (Django):
      - Описание: lab2/docs/index.md
      - Задание 2.1: lab2/docs/practice2_1.md
      - Задание 2.2: lab2/docs/practice2_2.md
      - Задание 2.3: lab2/docs/practice2_3.md
  - Лабораторная работа №3 (DRF):
      - Главная: lab3/index.md
      - Быстрый старт: lab3/quickstart.md
      - Тестирование: lab3/testing.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - tables

plugins:
  - search:
      lang: ru
